# Project: ÏîÄ¿1
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = stack.o main.o
LINKOBJ  = stack.o main.o
LIBS     = -L"D:/MyDownloads/Download/devcpp_setup/devcpp_setup/MinGW64/lib" -L"D:/MyDownloads/Download/devcpp_setup/devcpp_setup/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -pg -g3
INCS     = -I"D:/MyDownloads/Download/devcpp_setup/devcpp_setup/MinGW64/include" -I"D:/MyDownloads/Download/devcpp_setup/devcpp_setup/MinGW64/x86_64-w64-mingw32/include" -I"D:/MyDownloads/Download/devcpp_setup/devcpp_setup/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/MyDownloads/Download/devcpp_setup/devcpp_setup/MinGW64/include" -I"D:/MyDownloads/Download/devcpp_setup/devcpp_setup/MinGW64/x86_64-w64-mingw32/include" -I"D:/MyDownloads/Download/devcpp_setup/devcpp_setup/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/MyDownloads/Download/devcpp_setup/devcpp_setup/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Õ».exe
CXXFLAGS = $(CXXINCS) -pg -g3
CFLAGS   = $(INCS) -pg -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

stack.o: stack.c
	$(CC) -c stack.c -o stack.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
